### ISSUE TITLE
Excessive menu items

### ISSUE THREAD

**Issue by tripflex** [cliffordp/tk-event-weather#8]
What's with excessive menu items for the plugin?  IMO all your submenu items should be on the actual page ... once you have a good bit of plugins installed the settings menu item can already be overloaded, and using your plugin adds 4 extra menu items .... just sayin ....

**Comment by cliffordp** [comment]
Hi @tripflex. Thanks for your feedback. Personally, I agree. Those extra menu items are added by the integration with [Freemius](https://github.com/Freemius/wordpress-sdk/).

I added a new issue there: https://github.com/Freemius/wordpress-sdk/issues/85

If you have anything specific for my plugin's code, feel free to add a pull request. Thanks!
